Repository jwithers/citests, pull requests merged in 2022-01, with the labels that each got.

#42 fork pr for triggering
  feature1.txt
Labels: ci:run, ci:artifact, ci:ready_to_merge

#41 change to trigger pr
  feature3.txt
Labels: ci:run, ci:reviewed, ci:ready_to_merge

#43 triggering ci 46
  feature2.txt
Labels: ci:run, ci:ready_to_merge
